name: Flutter Leaflet and CD

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Flutter (Android App)
    runs-on: ubuntu-latest

    steps:
      - name: CHECKOUT (Step 1)
      - uses: actions/checkout@v1

      - name: SETUP JAVA (Step 2)
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: FLUTTER STABLE CHANNEL (Step 3)
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: FLUTTER PACKAGES GET (Step 4)
      - run: flutter pub get

      - name: FLUTTER BUILD (Step 5)
      - run: flutter build appbundle --release

      - name: Archive Flutter Android Artifact (Step 6)
        uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/apk/release
